# playground_db.py
# 문헌(Literature) Playground CRUD — Claude 기반 연구공간.
# 스키마: supabase_schema.sql 의 playgrounds / playground_messages / playground_papers.
# DB 접근 단일 진입점: db_config.get_engine() (database.py 와 동일 패턴).
from __future__ import annotations

from sqlalchemy import text, bindparam

from db_config import get_engine


# ── 스키마 보장(멱등) — 배포 DB 에 새 테이블이 없을 때 대비 ──
_PLAYGROUND_DDL = """
CREATE TABLE IF NOT EXISTS playgrounds (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT REFERENCES playgrounds(id) ON DELETE CASCADE,
    uniprot_id  TEXT,
    name        TEXT NOT NULL,
    digest      TEXT,
    digest_updated_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_playgrounds_uniprot ON playgrounds(uniprot_id);
CREATE INDEX IF NOT EXISTS idx_playgrounds_parent  ON playgrounds(parent_id);
CREATE TABLE IF NOT EXISTS playground_messages (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playground_id BIGINT NOT NULL REFERENCES playgrounds(id) ON DELETE CASCADE,
    role          TEXT NOT NULL,
    content       TEXT,
    created_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_playground_messages_pg ON playground_messages(playground_id);
CREATE TABLE IF NOT EXISTS playground_papers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playground_id BIGINT NOT NULL REFERENCES playgrounds(id) ON DELETE CASCADE,
    title         TEXT,
    doi           TEXT,
    storage_path  TEXT,
    matched_structure_id TEXT,
    matched       BOOLEAN DEFAULT FALSE,
    created_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_playground_papers_pg ON playground_papers(playground_id);
"""

_ensured = False


def ensure_playground_schema() -> None:
    """새 Playground 테이블이 없으면 생성(멱등). 최초 1회만 실행."""
    global _ensured
    if _ensured:
        return
    try:
        with get_engine().begin() as conn:
            conn.exec_driver_sql(_PLAYGROUND_DDL)
        _ensured = True
    except Exception as e:
        print(f"[WARN] Playground 스키마 보장 실패: {e}")


# ═══════════════════════════════════════════
# playgrounds
# ═══════════════════════════════════════════
def create_playground(uniprot_id: str, name: str, parent_id=None) -> int:
    """Playground 생성 → 새 id 반환. parent_id 지정 시 중첩(하위)."""
    ensure_playground_schema()
    with get_engine().begin() as conn:
        row = conn.execute(text("""
            INSERT INTO playgrounds (uniprot_id, name, parent_id)
            VALUES (:uid, :name, :pid)
            RETURNING id
        """), {"uid": uniprot_id or None, "name": (name or "새 주제").strip(),
               "pid": parent_id}).first()
    return int(row[0]) if row else 0


def list_playgrounds(uniprot_id: str) -> list[dict]:
    """이 단백질의 모든 Playground (트리 구성용 — parent_id 포함), 생성순."""
    ensure_playground_schema()
    with get_engine().connect() as conn:
        rows = conn.execute(text("""
            SELECT pg.id, pg.parent_id, pg.uniprot_id, pg.name,
                   (pg.digest IS NOT NULL AND pg.digest <> '') AS has_digest,
                   pg.digest_updated_at, pg.created_at,
                   (SELECT count(*) FROM playground_messages m
                      WHERE m.playground_id = pg.id) AS n_messages
            FROM playgrounds pg
            WHERE pg.uniprot_id = :uid OR (:uid IS NULL AND pg.uniprot_id IS NULL)
            ORDER BY pg.created_at ASC, pg.id ASC
        """), {"uid": uniprot_id or None}).mappings().all()
    out = []
    for r in rows:
        d = dict(r)
        d["id"] = int(d["id"])
        d["parent_id"] = int(d["parent_id"]) if d["parent_id"] is not None else 0
        d["name"] = d["name"] or "(이름 없음)"
        d["has_digest"] = bool(d["has_digest"])
        d["n_messages"] = int(d["n_messages"] or 0)
        d["created_at"] = str(d["created_at"]) if d["created_at"] else ""
        d["digest_updated_at"] = str(d["digest_updated_at"]) if d["digest_updated_at"] else ""
        out.append(d)
    return out


def get_playground(pid: int) -> dict | None:
    with get_engine().connect() as conn:
        row = conn.execute(text("""
            SELECT id, parent_id, uniprot_id, name, digest, digest_updated_at, created_at
            FROM playgrounds WHERE id = :id
        """), {"id": pid}).mappings().first()
    if not row:
        return None
    d = dict(row)
    d["id"] = int(d["id"])
    d["parent_id"] = int(d["parent_id"]) if d["parent_id"] is not None else 0
    d["name"] = d["name"] or "(이름 없음)"
    d["digest"] = d["digest"] or ""
    d["digest_updated_at"] = str(d["digest_updated_at"]) if d["digest_updated_at"] else ""
    return d


def rename_playground(pid: int, name: str) -> None:
    with get_engine().begin() as conn:
        conn.execute(text("UPDATE playgrounds SET name = :name WHERE id = :id"),
                     {"name": (name or "").strip() or "새 주제", "id": pid})


def update_digest(pid: int, digest: str) -> None:
    with get_engine().begin() as conn:
        conn.execute(text("""
            UPDATE playgrounds SET digest = :d, digest_updated_at = now() WHERE id = :id
        """), {"d": digest or "", "id": pid})


def delete_playground(pid: int) -> None:
    """Playground 삭제 (자식·메시지·문헌 cascade). Storage 객체도 정리."""
    # 하위 트리(자기 포함)의 storage_path 수집 → Storage 제거
    with get_engine().connect() as conn:
        ids = _descendant_ids(conn, pid)
        paths = []
        if ids:
            q = text("SELECT storage_path FROM playground_papers "
                     "WHERE playground_id IN :ids AND storage_path IS NOT NULL"
                     ).bindparams(bindparam("ids", expanding=True))
            paths = [r[0] for r in conn.execute(q, {"ids": ids}).all() if r[0]]
    if paths:
        try:
            from supabase_storage import _client, BUCKET
            _client().storage.from_(BUCKET).remove(paths)
        except Exception:
            pass
    with get_engine().begin() as conn:
        conn.execute(text("DELETE FROM playgrounds WHERE id = :id"), {"id": pid})


def _descendant_ids(conn, pid: int) -> list[int]:
    """pid 및 그 모든 하위 Playground id (재귀 CTE)."""
    rows = conn.execute(text("""
        WITH RECURSIVE tree AS (
            SELECT id FROM playgrounds WHERE id = :id
            UNION ALL
            SELECT pg.id FROM playgrounds pg JOIN tree t ON pg.parent_id = t.id
        )
        SELECT id FROM tree
    """), {"id": pid}).all()
    return [int(r[0]) for r in rows]


# ═══════════════════════════════════════════
# playground_messages
# ═══════════════════════════════════════════
def get_messages(pid: int) -> list[dict]:
    with get_engine().connect() as conn:
        rows = conn.execute(text("""
            SELECT id, role, content, created_at
            FROM playground_messages WHERE playground_id = :pid
            ORDER BY id ASC
        """), {"pid": pid}).mappings().all()
    out = []
    for r in rows:
        out.append({"id": int(r["id"]), "role": r["role"] or "user",
                    "content": r["content"] or "",
                    "created_at": str(r["created_at"]) if r["created_at"] else ""})
    return out


def add_message(pid: int, role: str, content: str) -> int:
    with get_engine().begin() as conn:
        row = conn.execute(text("""
            INSERT INTO playground_messages (playground_id, role, content)
            VALUES (:pid, :role, :content) RETURNING id
        """), {"pid": pid, "role": role, "content": content or ""}).first()
    return int(row[0]) if row else 0


def update_message(mid: int, content: str) -> None:
    with get_engine().begin() as conn:
        conn.execute(text("UPDATE playground_messages SET content = :c WHERE id = :id"),
                     {"c": content or "", "id": mid})


def delete_message(mid: int) -> None:
    with get_engine().begin() as conn:
        conn.execute(text("DELETE FROM playground_messages WHERE id = :id"), {"id": mid})


# ═══════════════════════════════════════════
# playground_papers (연결 문헌)
# ═══════════════════════════════════════════
def list_playground_papers(pid: int) -> list[dict]:
    with get_engine().connect() as conn:
        rows = conn.execute(text("""
            SELECT id, title, doi, storage_path, matched_structure_id, matched
            FROM playground_papers WHERE playground_id = :pid ORDER BY id ASC
        """), {"pid": pid}).mappings().all()
    out = []
    for r in rows:
        out.append({"id": int(r["id"]), "title": r["title"] or "(제목 없음)",
                    "doi": r["doi"] or "", "storage_path": r["storage_path"] or "",
                    "matched_structure_id": r["matched_structure_id"] or "",
                    "matched": bool(r["matched"])})
    return out


def add_playground_paper(pid: int, title: str, doi: str = "",
                         storage_path: str = "") -> int:
    with get_engine().begin() as conn:
        row = conn.execute(text("""
            INSERT INTO playground_papers (playground_id, title, doi, storage_path)
            VALUES (:pid, :title, :doi, :sp) RETURNING id
        """), {"pid": pid, "title": (title or "").strip(),
               "doi": (doi or "").strip(), "sp": storage_path or None}).first()
    return int(row[0]) if row else 0


def set_paper_match(paper_id: int, structure_id: str) -> None:
    with get_engine().begin() as conn:
        conn.execute(text("""
            UPDATE playground_papers
            SET matched_structure_id = :sid, matched = TRUE WHERE id = :id
        """), {"sid": structure_id, "id": paper_id})


def delete_playground_paper(paper_id: int) -> None:
    """연결 문헌 삭제 (+ Storage 객체 정리)."""
    with get_engine().connect() as conn:
        row = conn.execute(text("SELECT storage_path FROM playground_papers WHERE id = :id"),
                           {"id": paper_id}).first()
    sp = row[0] if row else None
    if sp:
        try:
            from supabase_storage import _client, BUCKET
            _client().storage.from_(BUCKET).remove([sp])
        except Exception:
            pass
    with get_engine().begin() as conn:
        conn.execute(text("DELETE FROM playground_papers WHERE id = :id"), {"id": paper_id})


# ═══════════════════════════════════════════
# 문헌 ↔ DB papers 매칭 (DOI 우선, 제목 폴백)
# ═══════════════════════════════════════════
def _norm_title(t: str) -> str:
    import re
    return re.sub(r"[^a-z0-9]", "", (t or "").lower())


def match_paper_to_db(uniprot_id: str, title: str = "", doi: str = "") -> dict | None:
    """업로드/참조 문헌을 이 단백질의 DB 논문과 대조.

    DOI 정확일치 우선, 없으면 제목 정규화 후 부분일치. 매칭 시:
    {structure_id, title, doi, has_structured} 반환, 없으면 None.
    """
    doi = (doi or "").strip().lower()
    with get_engine().connect() as conn:
        if doi:
            row = conn.execute(text("""
                SELECT ps.structure_id, p.title, ps.doi,
                       (pa.structured IS NOT NULL) AS has_structured
                FROM pdb_structures ps
                LEFT JOIN papers p ON p.structure_id = ps.structure_id
                LEFT JOIN paper_analysis pa ON pa.structure_id = ps.structure_id
                WHERE ps.uniprot_id = :uid AND lower(ps.doi) = :doi
                LIMIT 1
            """), {"uid": uniprot_id, "doi": doi}).mappings().first()
            if row:
                return {"structure_id": row["structure_id"], "title": row["title"] or "",
                        "doi": row["doi"] or "", "has_structured": bool(row["has_structured"])}
        # 제목 폴백
        nt = _norm_title(title)
        if len(nt) >= 12:
            rows = conn.execute(text("""
                SELECT p.structure_id, p.title, ps.doi,
                       (pa.structured IS NOT NULL) AS has_structured
                FROM papers p
                JOIN pdb_structures ps ON p.structure_id = ps.structure_id
                LEFT JOIN paper_analysis pa ON pa.structure_id = p.structure_id
                WHERE ps.uniprot_id = :uid AND p.title IS NOT NULL
            """), {"uid": uniprot_id}).mappings().all()
            for r in rows:
                cand = _norm_title(r["title"])
                if cand and (cand in nt or nt in cand):
                    return {"structure_id": r["structure_id"], "title": r["title"] or "",
                            "doi": r["doi"] or "", "has_structured": bool(r["has_structured"])}
    return None
