-- ============================================================
-- Supabase (PostgreSQL) 스키마 — protein-construct-builder + paper-analyzer 통합
-- UNIFIED_MIGRATION_PLAN.md §2 / §3 기준.
-- 사용법: Supabase 대시보드 → SQL Editor 에 붙여넣고 실행 (Stage 0).
--
-- 설계 메모:
--  - 자동증가 PK는 GENERATED BY DEFAULT AS IDENTITY 사용.
--    (데이터 이전 시 기존 id 값을 명시 삽입해야 하므로 BY DEFAULT. 이전 후 시퀀스 보정.)
--  - SQLite 구조/컬럼명은 그대로 보존. FK 관계는 명시적 제약으로 선언.
--  - 멱등 실행: CREATE TABLE IF NOT EXISTS.
-- ============================================================

-- ── 1. proteins ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS proteins (
    uniprot_id           TEXT PRIMARY KEY,
    gene_name            TEXT,
    protein_name         TEXT,
    organism             TEXT,
    sequence_path        TEXT,
    sequence_length      INTEGER,
    function_desc        TEXT,
    subcellular_location TEXT,
    signal_peptide       TEXT,
    created_at           TIMESTAMPTZ DEFAULT now()
);

-- ── 2. protein_domains ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS protein_domains (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uniprot_id TEXT NOT NULL REFERENCES proteins(uniprot_id) ON DELETE CASCADE,
    name       TEXT,
    start_pos  INTEGER,
    end_pos    INTEGER
);
CREATE INDEX IF NOT EXISTS idx_protein_domains_uniprot ON protein_domains(uniprot_id);

-- ── 3. pdb_structures ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_structures (
    structure_id      TEXT PRIMARY KEY,
    uniprot_id        TEXT NOT NULL REFERENCES proteins(uniprot_id) ON DELETE CASCADE,
    source            TEXT,
    method            TEXT,
    resolution        DOUBLE PRECISION,
    mean_plddt        DOUBLE PRECISION,
    chain_id          TEXT,
    residue_range     TEXT,
    expression_system TEXT,
    host_cell_line    TEXT,
    crystal_method    TEXT,
    crystal_ph        DOUBLE PRECISION,
    crystal_temp      DOUBLE PRECISION,
    crystal_details   TEXT,
    space_group       TEXT,
    complex_type      TEXT,
    doi               TEXT,
    deposition_date   TEXT
);
CREATE INDEX IF NOT EXISTS idx_pdb_structures_uniprot ON pdb_structures(uniprot_id);

-- ── 4. structure_mutations ──────────────────────────────────
CREATE TABLE IF NOT EXISTS structure_mutations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id  TEXT NOT NULL REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    mutation      TEXT,
    position      INTEGER,
    mutation_type TEXT
);
CREATE INDEX IF NOT EXISTS idx_structure_mutations_sid ON structure_mutations(structure_id);

-- ── 5. ligands ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ligands (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id TEXT NOT NULL REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    ligand_id    TEXT,
    ligand_name  TEXT,
    formula      TEXT,
    smiles       TEXT,
    ligand_type  TEXT
);
CREATE INDEX IF NOT EXISTS idx_ligands_sid ON ligands(structure_id);

-- ── 6. partner_proteins ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS partner_proteins (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id              TEXT NOT NULL REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    entity_id                 TEXT,
    partner_uniprot_id        TEXT,
    partner_gene_name         TEXT,
    partner_chain_id          TEXT,
    sequence_length           INTEGER,
    organism                  TEXT,
    partner_residue_range     TEXT,
    partner_expression_system TEXT
);
CREATE INDEX IF NOT EXISTS idx_partner_proteins_sid ON partner_proteins(structure_id);

-- ── 7. partner_protein_chains ───────────────────────────────
CREATE TABLE IF NOT EXISTS partner_protein_chains (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT NOT NULL REFERENCES partner_proteins(id) ON DELETE CASCADE,
    chain_id   TEXT
);
CREATE INDEX IF NOT EXISTS idx_partner_chains_pid ON partner_protein_chains(partner_id);

-- ── 8. ptm_oligosaccharides ─────────────────────────────────
CREATE TABLE IF NOT EXISTS ptm_oligosaccharides (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id    TEXT NOT NULL REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    entity_id       TEXT,
    name            TEXT,
    chain_id        TEXT,
    linked_chain    TEXT,
    linked_position INTEGER,
    linked_residue  TEXT
);
CREATE INDEX IF NOT EXISTS idx_ptm_oligo_sid ON ptm_oligosaccharides(structure_id);

-- ── 9. klifs_structures ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS klifs_structures (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id     TEXT NOT NULL UNIQUE REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    klifs_id         INTEGER,
    kinase_id        INTEGER,
    kinase_name      TEXT,
    family           TEXT,
    dfg              TEXT,
    ac_helix         TEXT,
    qualityscore     DOUBLE PRECISION,
    missing_residues INTEGER,
    missing_atoms    INTEGER,
    rmsd1            DOUBLE PRECISION,
    rmsd2            DOUBLE PRECISION,
    gatekeeper       TEXT
);

-- ── 10. paper_analysis ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_analysis (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id TEXT NOT NULL UNIQUE REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    pdf_path     TEXT,
    status       TEXT DEFAULT 'none',
    raw_text     TEXT,
    analyzed_at  TIMESTAMPTZ
);

-- ── 11. app_state ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS app_state (
    key   TEXT PRIMARY KEY,
    value TEXT
);

-- ============================================================
-- 신규 테이블 (통합으로 추가) — UNIFIED_MIGRATION_PLAN.md §2-B
-- ============================================================

-- ── 12. papers ── paper-analyzer 파이프라인 출력 (Google Sheets index 대체)
CREATE TABLE IF NOT EXISTS papers (
    paper_id        TEXT PRIMARY KEY,
    title           TEXT,
    doi             TEXT,
    authors         TEXT,
    analyzed_at     TIMESTAMPTZ,
    model           TEXT,
    language        TEXT,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    cost_usd        DOUBLE PRECISION,
    analysis_md     TEXT,
    pdf_object_path TEXT,                      -- Supabase Storage 경로(또는 NULL)
    tags            TEXT,
    structure_id    TEXT REFERENCES pdb_structures(structure_id) ON DELETE SET NULL,  -- 선택적 PDB 연결
    created_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_papers_structure ON papers(structure_id);
CREATE INDEX IF NOT EXISTS idx_papers_doi ON papers(doi);

-- ── 13. chats ── AI 질의 기록 (chat_history.json 대체)
CREATE TABLE IF NOT EXISTS chats (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question            TEXT,
    answer              TEXT,
    queries             JSONB DEFAULT '[]'::jsonb,   -- [{sql, rows, error}, ...]
    error               TEXT,
    related_uniprot_ids JSONB DEFAULT '[]'::jsonb,
    created_at          TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chats_created ON chats(created_at DESC);

-- ============================================================
-- Phase 3 — Knowledge Base (REFLEX_UNIFIED_PLAN.md)
-- pgvector 의미검색 + 주제(Topic) 기반 지식 누적. 임베딩 384차원(local multilingual MiniLM).
-- ============================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ── 14. topics ──
CREATE TABLE IF NOT EXISTS topics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- ── 15. topic_links ── 주제 ↔ (protein|structure|paper|insight) 연결
CREATE TABLE IF NOT EXISTS topic_links (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id    BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    entity_type TEXT NOT NULL,
    entity_id   TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_topic_links_topic ON topic_links(topic_id);

-- ── 16. insights ── LLM 교차 종합 노트
CREATE TABLE IF NOT EXISTS insights (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id   BIGINT REFERENCES topics(id) ON DELETE CASCADE,
    title      TEXT,
    body       TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ── 17. embeddings ── 의미검색 인덱스 (pgvector)
CREATE TABLE IF NOT EXISTS embeddings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL,        -- 'paper'|'insight'|'structure'|...
    source_id   TEXT NOT NULL,
    chunk_text  TEXT,
    embedding   vector(384),
    created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_embeddings_source ON embeddings(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_embeddings_vec ON embeddings USING hnsw (embedding vector_cosine_ops);

-- ============================================================
-- 검증 쿼리 (실행 후 17개 테이블 확인)
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema='public' ORDER BY table_name;
-- ============================================================
