-- ============================================================
-- Supabase (PostgreSQL) 스키마 — protein-construct-builder + paper-analyzer 통합
-- UNIFIED_MIGRATION_PLAN.md §2 / §3 기준.
-- 사용법: Supabase 대시보드 → SQL Editor 에 붙여넣고 실행 (Stage 0).
--
-- 설계 메모:
--  - 자동증가 PK는 GENERATED BY DEFAULT AS IDENTITY 사용.
--    (데이터 이전 시 기존 id 값을 명시 삽입해야 하므로 BY DEFAULT. 이전 후 시퀀스 보정.)
--  - SQLite 구조/컬럼명은 그대로 보존. FK 관계는 명시적 제약으로 선언.
--  - 멱등 실행: CREATE TABLE IF NOT EXISTS.
-- ============================================================

-- ── 1. proteins ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS proteins (
    uniprot_id           TEXT PRIMARY KEY,
    gene_name            TEXT,
    protein_name         TEXT,
    organism             TEXT,
    sequence_path        TEXT,
    sequence_length      INTEGER,
    function_desc        TEXT,
    subcellular_location TEXT,
    signal_peptide       TEXT,
    created_at           TIMESTAMPTZ DEFAULT now()
);

-- ── 2. protein_domains ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS protein_domains (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uniprot_id TEXT NOT NULL REFERENCES proteins(uniprot_id) ON DELETE CASCADE,
    name       TEXT,
    start_pos  INTEGER,
    end_pos    INTEGER
);
CREATE INDEX IF NOT EXISTS idx_protein_domains_uniprot ON protein_domains(uniprot_id);

-- ── 3. pdb_structures ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_structures (
    structure_id      TEXT PRIMARY KEY,
    uniprot_id        TEXT NOT NULL REFERENCES proteins(uniprot_id) ON DELETE CASCADE,
    source            TEXT,
    method            TEXT,
    resolution        DOUBLE PRECISION,
    mean_plddt        DOUBLE PRECISION,
    chain_id          TEXT,
    residue_range     TEXT,
    expression_system TEXT,
    host_cell_line    TEXT,
    crystal_method    TEXT,
    crystal_ph        DOUBLE PRECISION,
    crystal_temp      DOUBLE PRECISION,
    crystal_details   TEXT,
    space_group       TEXT,
    complex_type      TEXT,
    doi               TEXT,
    deposition_date   TEXT
);
CREATE INDEX IF NOT EXISTS idx_pdb_structures_uniprot ON pdb_structures(uniprot_id);

-- ── 4. structure_mutations ──────────────────────────────────
CREATE TABLE IF NOT EXISTS structure_mutations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id  TEXT NOT NULL REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    mutation      TEXT,
    position      INTEGER,
    mutation_type TEXT
);
CREATE INDEX IF NOT EXISTS idx_structure_mutations_sid ON structure_mutations(structure_id);

-- ── 5. ligands ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ligands (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id TEXT NOT NULL REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    ligand_id    TEXT,
    ligand_name  TEXT,
    formula      TEXT,
    smiles       TEXT,
    ligand_type  TEXT,
    inchikey     TEXT     -- RCSB chemcomp InChIKey (ChEMBL 화합물과 구조 동일성 매칭용)
);
CREATE INDEX IF NOT EXISTS idx_ligands_sid ON ligands(structure_id);
ALTER TABLE ligands ADD COLUMN IF NOT EXISTS inchikey TEXT;
CREATE INDEX IF NOT EXISTS idx_ligands_inchikey ON ligands(inchikey);

-- ── 6. partner_proteins ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS partner_proteins (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id              TEXT NOT NULL REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    entity_id                 TEXT,
    partner_uniprot_id        TEXT,
    partner_gene_name         TEXT,
    partner_chain_id          TEXT,
    sequence_length           INTEGER,
    organism                  TEXT,
    partner_residue_range     TEXT,
    partner_expression_system TEXT
);
CREATE INDEX IF NOT EXISTS idx_partner_proteins_sid ON partner_proteins(structure_id);

-- ── 7. partner_protein_chains ───────────────────────────────
CREATE TABLE IF NOT EXISTS partner_protein_chains (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT NOT NULL REFERENCES partner_proteins(id) ON DELETE CASCADE,
    chain_id   TEXT
);
CREATE INDEX IF NOT EXISTS idx_partner_chains_pid ON partner_protein_chains(partner_id);

-- ── 8. ptm_oligosaccharides ─────────────────────────────────
CREATE TABLE IF NOT EXISTS ptm_oligosaccharides (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id    TEXT NOT NULL REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    entity_id       TEXT,
    name            TEXT,
    chain_id        TEXT,
    linked_chain    TEXT,
    linked_position INTEGER,
    linked_residue  TEXT
);
CREATE INDEX IF NOT EXISTS idx_ptm_oligo_sid ON ptm_oligosaccharides(structure_id);

-- ── 9. klifs_structures ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS klifs_structures (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id     TEXT NOT NULL UNIQUE REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    klifs_id         INTEGER,
    kinase_id        INTEGER,
    kinase_name      TEXT,
    family           TEXT,
    dfg              TEXT,
    ac_helix         TEXT,
    qualityscore     DOUBLE PRECISION,
    missing_residues INTEGER,
    missing_atoms    INTEGER,
    rmsd1            DOUBLE PRECISION,
    rmsd2            DOUBLE PRECISION,
    gatekeeper       TEXT
);

-- ── 10. paper_analysis ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_analysis (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    structure_id TEXT NOT NULL UNIQUE REFERENCES pdb_structures(structure_id) ON DELETE CASCADE,
    pdf_path     TEXT,
    status       TEXT DEFAULT 'none',
    raw_text     TEXT,
    structured   JSONB,   -- PDB별 논문 구조화 분석(주제/통찰/클로닝/발현/정제/결정화/어세이)
    pdf_bytes    BYTEA,   -- (레거시) 업로드 PDF 원본. 대용량은 Storage 사용.
    pdf_name     TEXT,
    pdf_storage_path TEXT, -- Supabase Storage 경로(대용량 PDF, Cloud 크기한계 우회)
    analyzed_at  TIMESTAMPTZ
);
ALTER TABLE paper_analysis ADD COLUMN IF NOT EXISTS pdf_storage_path TEXT;

-- ── 11. app_state ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS app_state (
    key   TEXT PRIMARY KEY,
    value TEXT
);

-- ============================================================
-- 신규 테이블 (통합으로 추가) — UNIFIED_MIGRATION_PLAN.md §2-B
-- ============================================================

-- ── 12. papers ── paper-analyzer 파이프라인 출력 (Google Sheets index 대체)
CREATE TABLE IF NOT EXISTS papers (
    paper_id        TEXT PRIMARY KEY,
    title           TEXT,
    doi             TEXT,
    authors         TEXT,
    analyzed_at     TIMESTAMPTZ,
    model           TEXT,
    language        TEXT,
    input_tokens    INTEGER,
    output_tokens   INTEGER,
    cost_usd        DOUBLE PRECISION,
    analysis_md     TEXT,
    pdf_object_path TEXT,                      -- Supabase Storage 경로(또는 NULL)
    tags            TEXT,
    structure_id    TEXT REFERENCES pdb_structures(structure_id) ON DELETE SET NULL,  -- 선택적 PDB 연결
    created_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_papers_structure ON papers(structure_id);
CREATE INDEX IF NOT EXISTS idx_papers_doi ON papers(doi);

-- ── 13. chats ── AI 질의 기록 (chat_history.json 대체)
CREATE TABLE IF NOT EXISTS chats (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question            TEXT,
    answer              TEXT,
    queries             JSONB DEFAULT '[]'::jsonb,   -- [{sql, rows, error}, ...]
    error               TEXT,
    related_uniprot_ids JSONB DEFAULT '[]'::jsonb,
    created_at          TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chats_created ON chats(created_at DESC);

-- ============================================================
-- Phase 3 — Knowledge Base (REFLEX_UNIFIED_PLAN.md)
-- pgvector 의미검색 + 주제(Topic) 기반 지식 누적. 임베딩 384차원(local multilingual MiniLM).
-- ============================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- ── 14. topics ──
CREATE TABLE IF NOT EXISTS topics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- ── 15. topic_links ── 주제 ↔ (protein|structure|paper|insight) 연결
CREATE TABLE IF NOT EXISTS topic_links (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id    BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    entity_type TEXT NOT NULL,
    entity_id   TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_topic_links_topic ON topic_links(topic_id);

-- ── 16. insights ── LLM 교차 종합 노트
CREATE TABLE IF NOT EXISTS insights (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id   BIGINT REFERENCES topics(id) ON DELETE CASCADE,
    title      TEXT,
    body       TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ── 17. embeddings ── 의미검색 인덱스 (pgvector)
CREATE TABLE IF NOT EXISTS embeddings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type TEXT NOT NULL,        -- 'paper'|'insight'|'structure'|...
    source_id   TEXT NOT NULL,
    chunk_text  TEXT,
    embedding   vector(384),
    created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_embeddings_source ON embeddings(source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_embeddings_vec ON embeddings USING hnsw (embedding vector_cosine_ops);

-- ============================================================
-- 검증 쿼리 (실행 후 17개 테이블 확인)
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema='public' ORDER BY table_name;
-- ============================================================

-- ============================================================
-- R4 — Custom LLM (트리형 대화방)
-- ============================================================
CREATE TABLE IF NOT EXISTS llm_rooms (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES llm_rooms(id) ON DELETE CASCADE,
    title     TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS llm_messages (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id   BIGINT NOT NULL REFERENCES llm_rooms(id) ON DELETE CASCADE,
    role      TEXT NOT NULL,   -- 'user'|'assistant'|'insight'
    content   TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_llm_messages_room ON llm_messages(room_id);

-- ============================================================
-- cMET MVP v2 — ChEMBL 약물·활성 데이터 [C1, C2]
-- ============================================================

-- ── compounds ── ChEMBL 약물 기본 정보
CREATE TABLE IF NOT EXISTS compounds (
    chembl_id        TEXT PRIMARY KEY,
    pref_name        TEXT,
    canonical_smiles TEXT,
    inchikey         TEXT,
    max_phase        NUMERIC,  -- ChEMBL max_phase 는 0.5/4.0 등 소수 가능
    molecule_type    TEXT,     -- 'Small molecule'|'Antibody' 등
    clinical_status  TEXT      -- '진행중'|'중단'|'승인 완료' (CT.gov 기반)
);
-- 이전 버전(INTEGER)으로 이미 생성된 경우 타입 보정 (멱등).
-- compound_activity_summary 뷰가 max_phase 에 의존하므로 뷰를 먼저 제거 후 ALTER (뷰는 아래에서 재생성).
DROP VIEW IF EXISTS compound_activity_summary;
ALTER TABLE compounds ALTER COLUMN max_phase TYPE NUMERIC USING max_phase::numeric;
ALTER TABLE compounds ADD COLUMN IF NOT EXISTS molecule_type   TEXT;
ALTER TABLE compounds ADD COLUMN IF NOT EXISTS clinical_status TEXT;
DROP TABLE IF EXISTS drug_indications CASCADE;   -- 대표 Indication 제거(요청)

-- 약물 임상시험 (ClinicalTrials.gov v2) — 임상 진행상황 파악
CREATE TABLE IF NOT EXISTS clinical_trials (
    nct_id         TEXT PRIMARY KEY,
    chembl_id      TEXT REFERENCES compounds(chembl_id) ON DELETE CASCADE,
    title          TEXT,
    phase          TEXT,
    overall_status TEXT,              -- RECRUITING/COMPLETED/TERMINATED 등
    conditions     TEXT,
    why_stopped    TEXT,              -- 중단 사유
    start_date     TEXT,
    fetched_at     TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_clinical_trials_chembl ON clinical_trials(chembl_id);

-- ── compound_synonyms ── 동의어 (임상명·INN·코드명)
CREATE TABLE IF NOT EXISTS compound_synonyms (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chembl_id TEXT NOT NULL REFERENCES compounds(chembl_id) ON DELETE CASCADE,
    synonym   TEXT,
    source    TEXT,
    UNIQUE(chembl_id, synonym)
);
CREATE INDEX IF NOT EXISTS idx_compound_synonyms_chembl ON compound_synonyms(chembl_id);

-- ── bioactivities ── ChEMBL 활성 데이터 (분해 저장) [C1]
CREATE TABLE IF NOT EXISTS bioactivities (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chembl_id           TEXT NOT NULL REFERENCES compounds(chembl_id) ON DELETE CASCADE,
    uniprot_acc         TEXT NOT NULL REFERENCES proteins(uniprot_id) ON DELETE CASCADE,
    standard_type       TEXT,
    standard_value      DOUBLE PRECISION,
    standard_units      TEXT,
    value_nM_normalized DOUBLE PRECISION,   -- NULL if non-concentration unit
    pchembl_value       DOUBLE PRECISION,
    assay_chembl_id     TEXT,
    assay_description   TEXT,
    document_chembl_id  TEXT,
    UNIQUE(chembl_id, uniprot_acc, assay_chembl_id, standard_type)
);
CREATE INDEX IF NOT EXISTS idx_bioactivities_uniprot ON bioactivities(uniprot_acc);
CREATE INDEX IF NOT EXISTS idx_bioactivities_chembl  ON bioactivities(chembl_id);

-- ── ligand_chembl_map ── PDB 리간드(CCD) ↔ ChEMBL 화합물 교차참조 (UniChem 캐시)
-- PDB 구조 ↔ 약물 연결의 다리. 매핑 없으면 chembl_id NULL sentinel 로 저장(재조회 방지).
CREATE TABLE IF NOT EXISTS ligand_chembl_map (
    ligand_id  TEXT PRIMARY KEY,   -- PDB CCD code (예: 'VGH')
    chembl_id  TEXT,               -- 매핑된 ChEMBL ID (없으면 NULL)
    source     TEXT DEFAULT 'unichem',
    checked_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ligand_chembl_map_chembl ON ligand_chembl_map(chembl_id);

-- ── compound_activity_summary view ── 약물당 대표값 [C2]
CREATE OR REPLACE VIEW compound_activity_summary AS
SELECT
    b.chembl_id,
    b.uniprot_acc,
    c.pref_name,
    c.max_phase,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY b.pchembl_value) AS median_pchembl,
    count(*)                                                        AS n_records,
    min(b.value_nM_normalized)                                      AS best_nM
FROM bioactivities b
JOIN compounds c ON b.chembl_id = c.chembl_id
WHERE b.pchembl_value IS NOT NULL
GROUP BY b.chembl_id, b.uniprot_acc, c.pref_name, c.max_phase;
